plugins {
    id 'java'
    id 'io.qameta.allure' version '2.12.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    testCompileOnly 'org.projectlombok:lombok:1.18.38'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'
    testImplementation 'io.rest-assured:rest-assured:5.5.6'
    testImplementation 'net.datafaker:datafaker:2.4.2'
    testImplementation 'org.slf4j:slf4j-simple:2.0.17'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.20.0'

    testImplementation 'org.apache.logging.log4j:log4j-api:2.24.3'
    testImplementation 'org.apache.logging.log4j:log4j-core:2.24.3'

    testImplementation 'io.qameta.allure:allure-junit5:2.29.1'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "failed", "skipped"
        showStandardStreams = true
    }
}

allure {
    version.set("2.35.0")
}